version: '3.8'

services:
  clip-bot:
    build: .
    container_name: clip-bot
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./downloads:/app/downloads
      - ./stats.json:/app/stats.json
      - ./cookies.txt:/app/cookies.txt
      - ./session.txt:/app/session.txt
    # Даем приложению знать, что оно в Docker (если нужно)
    environment:
      - NODE_ENV=production
